runtime: nodejs
env: flexible

env_variables:
  NODE_ENV: production

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 1
  cool_down_period_sec: 180
  cpu_utilization:
    target_utilization: 0.8

resources:
  cpu: 1
  memory_gb: 4
  disk_size_gb: 10

network:
  session_affinity: true

# Health check configuration  
readiness_check:
  path: "/health"
  check_interval_sec: 10
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2
  app_start_timeout_sec: 600

liveness_check:
  path: "/health" 
  check_interval_sec: 60
  timeout_sec: 10
  failure_threshold: 3
  success_threshold: 2